resources:
  - name: gitResource1
    type: GitRepo
    configuration:
      path: lidorv/aaa
      gitProvider: VCS_5
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: buildInfoResource1
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_5
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: Pipeline2
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: MvnBuild
        configuration:
          mvnCommand: install
          resolverSnapshotRepo: dvd
          resolverReleaseRepo: dvd
          deployerSnapshotRepo: dvd
          deployerReleaseRepo: dvd

          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: Artifactory_5
          inputResources:
            - name: gitResource1
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: gitResource1
          outputResources:
            - name: buildInfoResource1
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status gitResource1
